name: newapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.2
  shimmer: ^3.0.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Utilities
  dartz: ^0.10.1
  intl: ^0.19.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

  # Lint & Analysis
  custom_lint: ^0.6.4
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
